# .air.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "swag init && go build -o ./tmp/main ."
bin = "tmp/main"

exclude_dir = ["assets", "tmp", "vendor", "frontend"]
exclude_file = ["*.tmp", "*.temp", "*.~", "*~"]

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[log]
time = true
