info:
  contact: {}
paths:
  /changePassword:
    post:
      consumes:
      - application/json
      description: 修改用户的密码。
      parameters:
      - description: 用户名
        in: body
        name: username
        required: true
        schema:
          type: string
      - description: 旧密码
        in: body
        name: oldPassword
        required: true
        schema:
          type: string
      - description: 新密码
        in: body
        name: newPassword
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: message:密码修改成功
          schema:
            additionalProperties: true
            type: object
        "400":
          description: error:错误信息
          schema:
            additionalProperties: true
            type: object
      tags:
      - 用户
  /login:
    post:
      consumes:
      - application/json
      description: 用户登录，成功返回 JWT 令牌。
      parameters:
      - description: 用户名
        in: body
        name: username
        required: true
        schema:
          type: string
      - description: 密码
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: token:JWT令牌
          schema:
            additionalProperties: true
            type: object
        "401":
          description: error:认证失败的错误信息
          schema:
            additionalProperties: true
            type: object
      summary: 用户登录
      tags:
      - 用户
  /register:
    post:
      consumes:
      - application/json
      description: 用户注册。
      parameters:
      - description: 用户名
        in: body
        name: username
        required: true
        schema:
          type: string
      - description: 密码
        in: body
        name: password
        required: true
        schema:
          type: string
      - description: 邮箱
        in: body
        name: email
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: message:注册成功
          schema:
            additionalProperties: true
            type: object
        "400":
          description: error:错误信息
          schema:
            additionalProperties: true
            type: object
      summary: 注册新用户
      tags:
      - 用户
swagger: "2.0"
